# allow to run without specifying the target triple
[build]
# target = "thumbv7em-none-eabihf" # for setting up the freestanding rust binary
target = "x86_64-nacho_os.json" # for setting up the kernel
